### ISSUE TITLE
Privacy statements are incomplete.

### ISSUE THREAD

**Issue by milovanderlinden** [CodeForEindhoven/open311-android#12]
I think that the privacy statements in the application are weak.
- We do not explain what we store and why, but we tell in paragraph 1 that we will give full disclosure.
- Some sentences are duplicates of the previous, only using other words.

**Comment by basbiezemans** [comment]
It's not an actual privacy statement, just filler text. A legal department can provide a real privacy statement that applies to the situation at hand.
